### PR TITLE
Russian Added

### PR DESCRIPTION
**Pull request by Oyne**
1 Gen
Full log book
Hotkey Settings
localeSync Config

### CODE REVIEW

**Comment by Aegyo** [comment]
I see that the pokemon file here has English names for everything you haven't translated yet, isn't that going to make it difficult to spot ones that still need translating?

**Comment by Aegyo** [comment]
Oh, and could you comment with a link to some resource providing the russian pokemon names?

**Comment by Oyne** [comment]
https://www.orthrusonline.ru/dex/gen-1
https://ru.pokelore.com/pokedex
https://pokemon.fandom.com/ru/wiki/Pokemon_Wiki
Anime names
Translations of roms(like fire red, emerald, and that stuff)
I fixed some of names from thesee sites cuz they were kinda stupid

**Comment by Oyne** [comment]
> 

I don`t think so, I`we done full gen 1, and do full 2 and so on, I also can see cyrillic letters, so this helps

**Review by Aegyo — APPROVED** [review]

**Pull request merged**
