### PR TITLE
Russian

### PR DESCRIPTION
**Pull request by Oyne**
1 Gen
All Log Book
Some settings

### CODE REVIEW

**Comment by Aegyo** [comment]
Please change the folder name to `ru`, and add `ru` into the [localeSync config](https://github.com/pokeclicker/pokeclicker-translations/blob/develop/config/localesSync.config.js#L3) language list.

**Comment by Oyne** [comment]
But I've done this

image

image

**Comment by Aegyo** [comment]
It doesn't look like that on this PR, did you push those changes up to your branch?

**Comment by Aegyo** [comment]
Looks like you've pushed that to your `rus` branch, but this PR has been made from your `ru` branch

**Comment by Oyne** [comment]
I pushed them on ru as I remember. I will remake PR, hope this will work

**Pull request closed without merging**
